#!/usr/bin/env bash
# E2E deploy test for issue #275.
#
# Proves the full flow from the MCM HTTP API down to a live Mosquitto
# broker on the dev Compose stack:
#
#   1. `docker compose up -d` brings up mcm + mosquitto on a clean repo.
#   2. The bootstrap admin password (auto-generated by MCM, logged once)
#      authenticates against POST /api/v1/auth/login.
#   3. POST /api/v1/mqtt-users creates a new MQTT user "e2e-user" with a
#      generated password; the response carries the cleartext password
#      we use for the broker-side checks below.
#   4. POST /api/v1/acls creates an ACL rule allowing "e2e-user" to
#      publish/subscribe to "e2e/test/allowed".
#   5. POST /api/v1/deployments/preview returns has_changes=true and the
#      expected diffs.
#   6. POST /api/v1/deployments/apply renders the passwd/acl files into
#      the shared volume and SIGHUPs the broker.
#   7. After a short settle delay, the broker accepts a publish from
#      e2e-user to e2e/test/allowed (allowed ACL) and rejects one to
#      e2e/test/forbidden (no ACL grant).
#
# Invariants asserted:
#   1. /livez returns 200 within the wait budget.
#   2. POST /auth/login returns 200 + token.
#   3. POST /mqtt-users returns 201 + user + password.
#   4. POST /deployments/preview returns 200 with has_changes=true.
#   5. POST /deployments/apply returns 200 with status="applied".
#   6. mosquitto_pub for the allowed topic succeeds (exit 0).
#   7. mosquitto_pub for the forbidden topic fails with a non-zero exit
#      and "not authorised" in stderr.
#   8. docker compose down -v cleans up.
#
# Exit code:
#   0  every invariant passed.
#   1  any invariant failed (see the failing step's stderr).
#
# Required: docker (compose v2), curl, jq. The script tries to install
# jq on the fly if missing.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE="docker compose"
PORT="${MCM_PORT:-8080}"
HOST_URL="http://localhost:${PORT}"

HEALTH_URL="${HOST_URL}/healthz"
LIVE_URL="${HOST_URL}/livez"
LOGIN_URL="${HOST_URL}/api/v1/auth/login"
MQTT_USERS_URL="${HOST_URL}/api/v1/mqtt-users"
ACLS_URL="${HOST_URL}/api/v1/acls"
DEPLOY_PREVIEW_URL="${HOST_URL}/api/v1/deployments/preview"
DEPLOY_APPLY_URL="${HOST_URL}/api/v1/deployments/apply"

# Wait budget (seconds). The compose healthcheck on mcm uses
# start_period=15s, retries=3, interval=30s — easily 60s+ cold. We
# poll /livez for up to 180s to give the buildx cache + DB init room.
WAIT_SECONDS="${E2E_DEPLOY_WAIT_SECONDS:-180}"

# The reload settle budget. SIGHUP is async; the broker needs a moment
# to re-read the password/acl files before the publish checks below
# can pass.
RELOAD_SETTLE_SECONDS="${E2E_DEPLOY_RELOAD_SETTLE:-5}"

# MQTT user we create via the API. The deploy apply writes this user
# into the broker's passwd file.
E2E_USER="${E2E_USER:-e2e-user}"
E2E_ALLOWED_TOPIC="${E2E_ALLOWED_TOPIC:-e2e/test/allowed}"
E2E_FORBIDDEN_TOPIC="${E2E_FORBIDDEN_TOPIC:-e2e/test/forbidden}"

cleanup() {
    local exit_code=$?
    echo "--- e2e-deploy: tearing down (exit=$exit_code) ---"
    (cd "$REPO_ROOT" && $COMPOSE down -v --remove-orphans >/dev/null 2>&1) || true
    exit "$exit_code"
}
trap cleanup EXIT

# Make sure jq is available. The CI image does not ship jq by default
# and `set -u` would catch its absence below.
if ! command -v jq >/dev/null 2>&1; then
    echo "--- e2e-deploy: installing jq ---"
    if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get update -qq && sudo apt-get install -y -qq jq
    elif command -v dnf >/dev/null 2>&1; then
        sudo dnf install -y jq
    elif command -v apk >/dev/null 2>&1; then
        sudo apk add --no-cache jq
    else
        echo "Cannot install jq: no supported package manager found" >&2
        exit 1
    fi
fi

cd "$REPO_ROOT"

# Sanity: require a clean repo so a leftover .env from a real operator
# does not silently mask a Compose regression.
if [ -f ".env" ]; then
    echo "Refusing to run: .env exists in repo root. Remove it before running the e2e deploy test." >&2
    exit 1
fi

echo "--- e2e-deploy: up (no env vars, image already loaded) ---"
# The mcm:dev image is already loaded by the CI step that downloaded
# the artifact from the image job. Rebuilding here would double the CI
# time and the previous flow did that redundantly. Locally (when
# running this script outside CI), the operator is expected to have
# built mcm:dev first (e.g. `task build` or `docker buildx build
# --load -t mcm:dev .`).
$COMPOSE up -d

echo "--- e2e-deploy: waiting for /livez (${WAIT_SECONDS}s budget) ---"
ready=0
for i in $(seq 1 "$WAIT_SECONDS"); do
    if curl -fsS "$LIVE_URL" >/dev/null 2>&1; then
        echo "livez ready after ${i}s"
        ready=1
        break
    fi
    sleep 1
done
if [ "$ready" -ne 1 ]; then
    echo "MCM did not become live within ${WAIT_SECONDS}s" >&2
    echo "--- mcm logs ---" >&2
    $COMPOSE logs --no-color mcm >&2 || true
    echo "--- mosquitto logs ---" >&2
    $COMPOSE logs --no-color mosquitto >&2 || true
    exit 1
fi

if ! curl -fsS "$HEALTH_URL" >/dev/null; then
    echo "healthz did not return 200" >&2
    exit 1
fi
echo "healthz OK"

echo "--- e2e-deploy: extracting bootstrap admin password from mcm logs ---"
# The bootstrap admin warn line is emitted exactly once on first boot:
#   {"time":"...","level":"WARN","msg":"bootstrap admin created; ...","username":"admin","password":"<...>"}
LOG_FILE="$(mktemp)"
$COMPOSE logs --no-color mcm > "$LOG_FILE" || true
if ! grep -q 'bootstrap admin created' "$LOG_FILE"; then
    echo "Expected bootstrap admin warn log line not found in mcm logs:" >&2
    cat "$LOG_FILE" >&2
    rm -f "$LOG_FILE"
    exit 1
fi

ADMIN_PASSWORD="$(grep 'bootstrap admin created' "$LOG_FILE" | sed -n 's/.*"password":"\([^"]*\)".*/\1/p' | head -n1)"
rm -f "$LOG_FILE"
if [ -z "$ADMIN_PASSWORD" ]; then
    echo "Could not extract bootstrap admin password from mcm logs" >&2
    exit 1
fi
echo "extracted admin password (length=${#ADMIN_PASSWORD})"

echo "--- e2e-deploy: POST /api/v1/auth/login ---"
login_body="$(mktemp)"
login_code="$(curl -sS -o "$login_body" -w '%{http_code}' \
    -X POST "$LOGIN_URL" \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"admin\",\"password\":\"${ADMIN_PASSWORD}\"}" || echo "000")"
if [ "$login_code" != "200" ]; then
    echo "login failed with HTTP $login_code:" >&2
    cat "$login_body" >&2
    rm -f "$login_body"
    exit 1
fi

TOKEN="$(jq -r '.token // .access_token // .jwt // empty' "$login_body")"
rm -f "$login_body"
if [ -z "$TOKEN" ]; then
    echo "login returned 200 but no token field was present" >&2
    exit 1
fi
echo "login OK, token length=${#TOKEN}"

auth_curl() {
    # $1 = method, $2 = path, $3 = body (or empty). Writes response to stdout.
    local method="$1"
    local path="$2"
    local body="${3:-}"
    if [ -n "$body" ]; then
        curl -sS -X "$method" "$HOST_URL$path" \
            -H "Authorization: Bearer ${TOKEN}" \
            -H 'Content-Type: application/json' \
            -d "$body"
    else
        curl -sS -X "$method" "$HOST_URL$path" \
            -H "Authorization: Bearer ${TOKEN}"
    fi
}

echo "--- e2e-deploy: POST /api/v1/mqtt-users (create ${E2E_USER}) ---"
mqtt_user_body="$(mktemp)"
user_code="$(curl -sS -o "$mqtt_user_body" -w '%{http_code}' \
    -X POST "$MQTT_USERS_URL" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"${E2E_USER}\"}" || echo "000")"
if [ "$user_code" != "201" ]; then
    echo "create mqtt-user failed with HTTP $user_code:" >&2
    cat "$mqtt_user_body" >&2
    rm -f "$mqtt_user_body"
    exit 1
fi

USER_PASSWORD="$(jq -r '.password // empty' "$mqtt_user_body")"
USER_ID="$(jq -r '.id // empty' "$mqtt_user_body")"
rm -f "$mqtt_user_body"
if [ -z "$USER_PASSWORD" ] || [ -z "$USER_ID" ]; then
    echo "create mqtt-user response missing password or id field" >&2
    exit 1
fi
echo "mqtt-user OK: id=${USER_ID}, password length=${#USER_PASSWORD}"

echo "--- e2e-deploy: POST /api/v1/acls (grant ${E2E_USER} on ${E2E_ALLOWED_TOPIC}) ---"
acl_body="$(mktemp)"
acl_code="$(curl -sS -o "$acl_body" -w '%{http_code}' \
    -X POST "$ACLS_URL" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H 'Content-Type: application/json' \
    -d "{\"principal\":\"${E2E_USER}\",\"topic_filter\":\"${E2E_ALLOWED_TOPIC}\",\"permission\":\"readwrite\"}" || echo "000")"
if [ "$acl_code" != "201" ]; then
    echo "create acl failed with HTTP $acl_code:" >&2
    cat "$acl_body" >&2
    rm -f "$acl_body"
    exit 1
fi
rm -f "$acl_body"
echo "acl OK"

echo "--- e2e-deploy: POST /api/v1/deployments/preview ---"
preview_body="$(mktemp)"
preview_code="$(curl -sS -o "$preview_body" -w '%{http_code}' \
    -X POST "$DEPLOY_PREVIEW_URL" \
    -H "Authorization: Bearer ${TOKEN}" || echo "000")"
if [ "$preview_code" != "200" ]; then
    echo "deploy preview failed with HTTP $preview_code:" >&2
    cat "$preview_body" >&2
    rm -f "$preview_body"
    exit 1
fi
HAS_CHANGES="$(jq -r '.has_changes // false' "$preview_body")"
rm -f "$preview_body"
if [ "$HAS_CHANGES" != "true" ]; then
    echo "expected deploy preview has_changes=true, got $HAS_CHANGES" >&2
    exit 1
fi
echo "preview OK, has_changes=true"

echo "--- e2e-deploy: POST /api/v1/deployments/apply ---"
apply_body="$(mktemp)"
apply_code="$(curl -sS -o "$apply_body" -w '%{http_code}' \
    -X POST "$DEPLOY_APPLY_URL" \
    -H "Authorization: Bearer ${TOKEN}" || echo "000")"
if [ "$apply_code" != "200" ]; then
    echo "deploy apply failed with HTTP $apply_code:" >&2
    cat "$apply_body" >&2
    rm -f "$apply_body"
    exit 1
fi
APPLY_STATUS="$(jq -r '.status // empty' "$apply_body")"
rm -f "$apply_body"
if [ "$APPLY_STATUS" != "applied" ]; then
    echo "expected deploy apply status=applied, got $APPLY_STATUS" >&2
    exit 1
fi
echo "apply OK, status=applied"

# Wait for the broker to settle after SIGHUP. The reload is async —
# without this delay the publish checks below race the reload.
echo "--- e2e-deploy: waiting ${RELOAD_SETTLE_SECONDS}s for broker reload to settle ---"
sleep "$RELOAD_SETTLE_SECONDS"

echo "--- e2e-deploy: verifying publish/subscribe on the live broker ---"
# Allowed: e2e-user can publish to the granted topic AND a subscriber
# receives the message. This is the strongest "publish succeeded" check
# we can run from a script — mosquitto_pub exits 0 even when the broker
# silently drops the publish because of an ACL denial, so the
# subscriber-based assertion below is the only reliable signal.
#
# We stream the subscriber's output back to the host via stdout. An
# earlier attempt used a host-mktemp file path inside the in-container
# sh, but the path was host-relative (`/tmp/...`) so the writes landed
# in the container's filesystem and the host grep saw nothing. Going
# through stdout keeps the path round-trip in the same namespace.
#
# The `|| true` at the end swallows the subscriber's exit code (which
# is non-zero on the timeout path) so `set -e` does not abort the
# script before we get a chance to grep the captured output.
allowed_log="$($COMPOSE exec -T mosquitto sh -c "
    mosquitto_sub -h 127.0.0.1 -p 1883 \
        -u \"$E2E_USER\" -P \"$USER_PASSWORD\" \
        -t \"$E2E_ALLOWED_TOPIC\" -C 1 -W 15 -q 1 2>&1 &
    SUB_PID=\$!
    # Wait for the subscriber to be ready: it must be subscribed BEFORE
    # we publish, otherwise QoS-0 publishes are lost.
    sleep 2
    mosquitto_pub -h 127.0.0.1 -p 1883 \
        -u \"$E2E_USER\" -P \"$USER_PASSWORD\" \
        -t \"$E2E_ALLOWED_TOPIC\" -m \"ok\" -q 1
    wait \$SUB_PID
" 2>&1 || true)"
if ! printf '%s\n' "$allowed_log" | grep -q '^ok$'; then
    echo "expected subscriber on allowed topic '$E2E_ALLOWED_TOPIC' to receive 'ok', got:" >&2
    printf '%s\n' "$allowed_log" >&2
    exit 1
fi
echo "allowed-topic publish+deliver OK"

# Forbidden: same user, no ACL grant → broker drops the publish. We
# can't rely on mosquitto_pub's exit code because Mosquitto silently
# drops ACL-denied messages (no error feedback). Instead, we run a
# subscriber on the forbidden topic, publish to it, and assert that
# the subscriber did NOT receive the message within the wait window.
# The `|| true` swallows the timeout exit code from mosquitto_sub.
forbidden_log="$($COMPOSE exec -T mosquitto sh -c "
    mosquitto_sub -h 127.0.0.1 -p 1883 \
        -u \"$E2E_USER\" -P \"$USER_PASSWORD\" \
        -t \"$E2E_FORBIDDEN_TOPIC\" -C 1 -W 8 -q 1 2>&1 &
    SUB_PID=\$!
    sleep 2
    mosquitto_pub -h 127.0.0.1 -p 1883 \
        -u \"$E2E_USER\" -P \"$USER_PASSWORD\" \
        -t \"$E2E_FORBIDDEN_TOPIC\" -m \"bad\" -q 1
    wait \$SUB_PID
" 2>&1 || true)"
# mosquitto_sub with -W prints "Timed out" on stderr when no message
# arrives. Either that, an empty payload, or an "Error: Connection …"
# line are all acceptable proof that the forbidden topic stayed quiet.
if printf '%s\n' "$forbidden_log" | grep -q '^bad$'; then
    echo "ACL leak: subscriber on forbidden topic '$E2E_FORBIDDEN_TOPIC' received 'bad'" >&2
    printf '%s\n' "$forbidden_log" >&2
    exit 1
fi
echo "forbidden-topic publish correctly dropped"

echo "--- e2e-deploy: all invariants passed ---"
